#
# Copyright 2021-2025 Software Radio Systems Limited
#
# This file is part of srsRAN
#
# srsRAN is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# srsRAN is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# A copy of the GNU Affero General Public License can be found in
# the LICENSE file in the top-level directory of this distribution
# and at http://www.gnu.org/licenses/.
#

# Build args
################
# OS_VERSION            Ubuntu OS version
# SRSRAN_REF            Git ref to build
# UHD_VERSION           UHD version number
# DPDK_VERSION          DPDK version number
# MARCH                 gcc/clang compatible arch
# NUM_JOBS              Number or empty for all
# EXTRA_CMAKE_ARGS      Extra flags for srsRAN Project
# FORCE_MIN_POOL_WORKERS Override srsRAN min_pool_workers in worker_manager.cpp

ARG OS_VERSION=24.04
# Using `main` ref because it has some ORAN/E2-related changes that are required to test srsRAN with the Aether SD-RAN (RIC)
ARG SRSRAN_REF=main
ARG UHD_VERSION=4.7.0.0
ARG DPDK_VERSION=23.11.1
ARG MARCH=native
ARG NUM_JOBS=""
ARG COMPILER=clang
ARG EXTRA_CMAKE_ARGS="-DENABLE_EXPORT=On -DENABLE_ZEROMQ=On"
ARG FORCE_MIN_POOL_WORKERS="4"

##################
# Stage 1: Build #
##################
FROM ubuntu:$OS_VERSION AS builder

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    git \
    git-lfs \
    ca-certificates

# Adding the complete repo to the context, in /src folder
# ADD . /src/
# An alternative could be to download the repo
ARG SRSRAN_REF
ARG FORCE_MIN_POOL_WORKERS
RUN git clone --depth 1 --branch ${SRSRAN_REF} https://github.com/srsran/srsRAN_Project.git /src && \
    if [ -n "${FORCE_MIN_POOL_WORKERS}" ]; then \
      sed -i "s/const unsigned min_pool_workers = 1;/const unsigned min_pool_workers = ${FORCE_MIN_POOL_WORKERS};/" \
        /src/apps/services/worker_manager/worker_manager.cpp && \
      grep -n "min_pool_workers" /src/apps/services/worker_manager/worker_manager.cpp; \
    fi

# Install srsRAN build dependencies
RUN /src/docker/scripts/install_dependencies.sh build && \
    /src/docker/scripts/install_uhd_dependencies.sh build && \
    /src/docker/scripts/install_dpdk_dependencies.sh build && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    git \
    clang \
    libzmq3-dev

ARG UHD_VERSION
ARG DPDK_VERSION
ARG MARCH
ARG NUM_JOBS

# Compile UHD/DPDK
RUN /src/docker/scripts/build_uhd.sh "${UHD_VERSION}" ${MARCH} ${NUM_JOBS} && \
    /src/docker/scripts/build_dpdk.sh "${DPDK_VERSION}" ${MARCH} ${NUM_JOBS}

# Compile srsRAN Project and install it in the OS
ARG COMPILER
ARG EXTRA_CMAKE_ARGS
ENV UHD_DIR=/opt/uhd/${UHD_VERSION}
ENV DPDK_DIR=/opt/dpdk/${DPDK_VERSION}
RUN if [ -z "$NUM_JOBS" ]; then NUM_JOBS=$(nproc); fi \
    && \
    /src/docker/scripts/builder.sh -c ${COMPILER} -m "-j${NUM_JOBS} srscu srsdu srsdu_split_8 srsdu_split_7_2 gnb gnb_split_8 gnb_split_7_2 ru_emulator" \
    -DBUILD_TESTS=False -DENABLE_UHD=On -DENABLE_DPDK=On -DMARCH=${MARCH} -DCMAKE_INSTALL_PREFIX=/opt/srs \
    ${EXTRA_CMAKE_ARGS} /src \
    && \
    mkdir -p /opt/srs/bin /opt/srs/share/srsran && \
    cp /src/build/apps/cu/srscu                 /opt/srs/bin/srscu            && \
    cp /src/build/apps/du/srsdu                 /opt/srs/bin/srsdu            && \
    cp /src/build/apps/du_split_8/srsdu         /opt/srs/bin/srsdu_split_8    && \
    cp /src/build/apps/du_split_7_2/srsdu       /opt/srs/bin/srsdu_split_7_2  && \
    cp /src/build/apps/gnb/gnb                  /opt/srs/bin/gnb              && \
    cp /src/build/apps/gnb_split_8/gnb          /opt/srs/bin/gnb_split_8      && \
    cp /src/build/apps/gnb_split_7_2/gnb        /opt/srs/bin/gnb_split_7_2    && \
    cp /src/build/apps/examples/ofh/ru_emulator /opt/srs/bin/ru_emulator      && \
    cp /src/configs/*.yml                       /opt/srs/share/srsran/

################
# Stage 2: Run #
################

FROM ubuntu:$OS_VERSION AS gnb

# Build arguments for dynamic labels
ARG VERSION=dev
ARG VCS_URL=unknown
ARG VCS_REF=unknown
ARG BUILD_DATE=unknown
ARG SRSRAN_REF
ARG UPSTREAM_COMMIT=unknown

LABEL org.opencontainers.image.source="${VCS_URL}" \
      org.opencontainers.image.version="${VERSION}" \
      org.opencontainers.image.created="${BUILD_DATE}" \
      org.opencontainers.image.revision="${VCS_REF}" \
      org.opencontainers.image.url="${VCS_URL}" \
      org.opencontainers.image.title="srsran-gnb" \
      org.opencontainers.image.description="srsRAN Project gNB" \
      org.opencontainers.image.authors="Aether SD-Core <dev@lists.aetherproject.org>" \
      org.opencontainers.image.vendor="Aether Project" \
      org.opencontainers.image.licenses="AGPL-3.0-or-later" \
      org.opencontainers.image.documentation="https://docs.srsran.com/projects/project" \
      org.srsran.upstream.source="https://github.com/srsran/srsRAN_Project.git" \
    org.srsran.upstream.ref="${SRSRAN_REF}" \
      org.srsran.upstream.commit="${UPSTREAM_COMMIT}"

ARG UHD_VERSION
ARG DPDK_VERSION

# Copy srsRAN binaries and libraries installed in previous stage
COPY --from=builder /opt/uhd/${UHD_VERSION}   /opt/uhd/${UHD_VERSION}
COPY --from=builder /opt/dpdk/${DPDK_VERSION} /opt/dpdk/${DPDK_VERSION}
COPY --from=builder /opt/srs                  /usr/local

ENV LD_LIBRARY_PATH=/opt/uhd/${UHD_VERSION}/lib/:/opt/uhd/${UHD_VERSION}/lib/x86_64-linux-gnu/:/opt/uhd/${UHD_VERSION}/lib/aarch64-linux-gnu/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
ENV LD_LIBRARY_PATH=/opt/dpdk/${DPDK_VERSION}/lib/:/opt/dpdk/${DPDK_VERSION}/lib/x86_64-linux-gnu/:/opt/dpdk/${DPDK_VERSION}/lib/aarch64-linux-gnu/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
ENV PATH=/opt/uhd/${UHD_VERSION}/bin/:/opt/dpdk/${DPDK_VERSION}/bin/${PATH:+:$PATH}

# Install srsran and lib runtime dependencies
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    libatomic1 \
    libdwarf1 \
    libnuma1 \
    libboost-chrono1.83.0t64 \
    libboost-filesystem1.83.0 \
    libboost-serialization1.83.0 \
    libboost-thread1.83.0 \
    libfdt1 \
    libfftw3-bin \
    libmbedtls14t64 \
    libsctp1 \
    libusb-1.0-0 \
    libyaml-cpp0.8 \
    libzmq5 \
    librte-net-mlx4-24 \
    cpufrequtils \
    inetutils-tools \
    iputils-ping \
    iproute2 && \
    apt-get autoremove && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
